### ISSUE TITLE
peewee.OperationalError: no such table: wiki

### ISSUE THREAD

**Issue by aquilesC** [syegulalp/folio#2]
I guess when starting the program for the first time, one should apply migrations to the database?

**Comment by syegulalp** [comment]
Hi there - was this when pulling from master, or using one of the release artifacts?

**Comment by syegulalp** [comment]
Sorry - if you're trying to use an earlier database, the schema will break, as it's pre-alpha. I noted this in the release notes for the most recent version. I'll go to full alpha when the schema is no longer in flux.

**Comment by aquilesC** [comment]
Just cloned the run, as you explain in the README, no previous version.

**Comment by syegulalp** [comment]
I just now pulled from master myself and was not able to reproduce the problem. Is this happening on first run?

**Comment by syegulalp** [comment]
Closing for now - pull afresh from master to try and reproduce it again if it's still giving you trouble.
