### ISSUE TITLE
No clear instructions for how to install on Linux or run from a cloned repo

### ISSUE THREAD

**Issue by johann-petrak** [syegulalp/folio#6]
I just tried to clone, install the requirements then run `python folio/` from within the repo dir and got an exception:

sqlite3.OperationalError: no such table: wiki

Why not have proper setup.py so it can be installed directly from the repo, and have setup.py install a command line handler? That would work on all systems.

**Comment by syegulalp** [comment]
I had intended at one point to restructure the project to do that, but I've at this point stopped work on Folio and moved all my note-taking work to Obsidian. It's been a while since I touched this repo; I'll be archiving it shortly.

**Comment by johann-petrak** [comment]
Thank you for that information!
